"""add courier live location fields

Revision ID: 29c225b5fbf3
Revises: 3c352cd6e0f7
Create Date: 2026-02-13 05:01:18.054914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c225b5fbf3'
down_revision = '3c352cd6e0f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courier_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('current_longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_location_update', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courier_profiles', schema=None) as batch_op:
        batch_op.drop_column('last_location_update')
        batch_op.drop_column('current_longitude')
        batch_op.drop_column('current_latitude')

    # ### end Alembic commands ###
