"""add assigned status and courier location fields

Revision ID: 3c352cd6e0f7
Revises: fix_notifications_schema
Create Date: 2026-02-10 11:21:11.884632

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '3c352cd6e0f7'
down_revision = 'fix_notifications_schema'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = inspect(bind)
    cols = {c['name'] for c in inspector.get_columns('delivery_orders')}

    with op.batch_alter_table('delivery_orders', schema=None) as batch_op:
        if 'current_latitude' not in cols:
            batch_op.add_column(sa.Column('current_latitude', sa.Numeric(precision=10, scale=8), nullable=True))
        if 'current_longitude' not in cols:
            batch_op.add_column(sa.Column('current_longitude', sa.Numeric(precision=11, scale=8), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_orders', schema=None) as batch_op:
        batch_op.drop_column('current_longitude')
        batch_op.drop_column('current_latitude')

    # ### end Alembic commands ###
