"""fix courier foreign key

Revision ID: 5be11687e9ca
Revises: b6d7548ee786
Create Date: 2026-02-06 16:28:59.393325

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '5be11687e9ca'
down_revision = 'b6d7548ee786'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = inspect(bind)
    fks = {fk.get('name') for fk in inspector.get_foreign_keys('delivery_orders')}

    with op.batch_alter_table('delivery_orders', schema=None) as batch_op:
        if 'fk_delivery_orders_courier_id_courier_profiles' in fks:
            batch_op.drop_constraint('fk_delivery_orders_courier_id_courier_profiles', type_='foreignkey')

        if 'fk_delivery_orders_courier_id_users' not in fks:
            batch_op.create_foreign_key(
                batch_op.f('fk_delivery_orders_courier_id_users'),
                'users',
                ['courier_id'],
                ['id']
            )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_delivery_orders_courier_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_delivery_orders_courier_id_courier_profiles', 'courier_profiles', ['courier_id'], ['id'])

    # ### end Alembic commands ###
