"""initial models

Revision ID: b6d7548ee786
Revises: 
Create Date: 2026-02-05 01:29:37.521422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6d7548ee786'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('courier', 'customer', 'admin', name='user_roles'), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('plate_number', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("(role != 'courier') OR (vehicle_type IS NOT NULL AND plate_number IS NOT NULL)", name=op.f('ck_users_ck_courier_vehicle_required')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('phone', name=op.f('uq_users_phone'))
    )
    op.create_table('courier_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('vehicle_registration', sa.String(length=50), nullable=True),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('total_deliveries', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_courier_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courier_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_courier_profiles_user_id'))
    )
    op.create_table('delivery_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_number', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('courier_id', sa.Integer(), nullable=True),
    sa.Column('pickup_lat', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('pickup_lng', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('pickup_address', sa.Text(), nullable=False),
    sa.Column('pickup_phone', sa.String(length=20), nullable=True),
    sa.Column('destination_lat', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('destination_lng', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('destination_address', sa.Text(), nullable=False),
    sa.Column('destination_phone', sa.String(length=20), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('weight_category', sa.Enum('SMALL', 'MEDIUM', 'LARGE', 'XLARGE', name='weightcategory'), nullable=False),
    sa.Column('parcel_description', sa.Text(), nullable=True),
    sa.Column('parcel_dimensions', sa.String(length=50), nullable=True),
    sa.Column('fragile', sa.Boolean(), nullable=True),
    sa.Column('insurance_required', sa.Boolean(), nullable=True),
    sa.Column('is_express', sa.Boolean(), nullable=True),
    sa.Column('is_weekend', sa.Boolean(), nullable=True),
    sa.Column('distance_km', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('distance_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('weight_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('extra_charges', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PICKED_UP', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED', name='orderstatus'), nullable=True),
    sa.Column('estimated_delivery_time', sa.DateTime(), nullable=True),
    sa.Column('actual_delivery_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['courier_id'], ['courier_profiles.id'], name=op.f('fk_delivery_orders_courier_id_courier_profiles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_delivery_orders_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delivery_orders')),
    sa.UniqueConstraint('tracking_number', name=op.f('uq_delivery_orders_tracking_number'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['delivery_orders.id'], name=op.f('fk_notifications_order_id_delivery_orders')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_table('order_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('location_description', sa.String(length=200), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PICKED_UP', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('speed_kmh', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('battery_level', sa.Integer(), nullable=True),
    sa.Column('accuracy_meters', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('courier_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['courier_id'], ['courier_profiles.id'], name=op.f('fk_order_tracking_courier_id_courier_profiles')),
    sa.ForeignKeyConstraint(['order_id'], ['delivery_orders.id'], name=op.f('fk_order_tracking_order_id_delivery_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_tracking'))
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('payment_method', sa.Enum('MPESA', 'CARD', 'CASH', 'WALLET', name='paymentmethod'), nullable=True),
    sa.Column('payment_status', sa.Enum('PENDING', 'PROCESSING', 'PAID', 'FAILED', 'REFUNDED', 'CANCELLED', name='paymentstatus'), nullable=True),
    sa.Column('transaction_reference', sa.String(length=100), nullable=True),
    sa.Column('merchant_request_id', sa.String(length=100), nullable=True),
    sa.Column('checkout_request_id', sa.String(length=100), nullable=True),
    sa.Column('mpesa_receipt_number', sa.String(length=100), nullable=True),
    sa.Column('card_last_four', sa.String(length=4), nullable=True),
    sa.Column('card_brand', sa.String(length=20), nullable=True),
    sa.Column('card_expiry_month', sa.Integer(), nullable=True),
    sa.Column('card_expiry_year', sa.Integer(), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('customer_email', sa.String(length=120), nullable=True),
    sa.Column('initiated_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('refund_reason', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('payment_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['delivery_orders.id'], name=op.f('fk_payments_order_id_delivery_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('order_id', name=op.f('uq_payments_order_id')),
    sa.UniqueConstraint('transaction_reference', name=op.f('uq_payments_transaction_reference'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('order_tracking')
    op.drop_table('notifications')
    op.drop_table('delivery_orders')
    op.drop_table('courier_profiles')
    op.drop_table('users')
    # ### end Alembic commands ###
